### ISSUE TITLE
stale and interpolated values

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#124]
The validator's detect stale and interpolated values functions flag points at night, though the details depend on the observation (two examples below). Is this desirable? Say you want to include nighttime values in your analysis but you want to exclude stale/interpolated points. You'd need to make a new flag `(STALE | INTERPOLATED) & ~NIGHTTIME`. If we wanted to exclude nighttime from the flag, then the detect functions would need to know when it was nighttime. So work to be done either way.

During the day, the stale/interpolated values functions sometimes flag data that is not actually stale or interpolated.

<img width="869" alt="Screen Shot 2019-06-06 at 1 22 20 PM" src="https://user-images.githubusercontent.com/4383303/59064379-faf25680-885e-11e9-908f-4c0d140cafb4.png">
<img width="990" alt="Screen Shot 2019-06-06 at 1 20 24 PM" src="https://user-images.githubusercontent.com/4383303/59064380-faf25680-885e-11e9-8984-bcaef3ef0089.png">

**Comment by alorenzo175** [comment]
I think the most flexible configuration will be to continue evaluating stale/interpolated, even at night, and make a new "flag" as appropriate for the particular evaluation scenario on the fly.  BTW for those two plots, the SRML data is filled with 0 at night while the OASIS sensor fluctuates a bit.

I agree that some adjustments in the algorithms might be needed for the daytime.

**Comment by cwhanse** [comment]
For the example above, I investigated the `detect_stale_values` behavior.  It's doing what I would expect: labeling the 3rd and later points as "stale" if the 3rd value is nearly equal to the previous 2 values. I extracted the GHI values from the time series near each of the "stale" values with GHI > 50 (pasted below). Actual measurements will vary slightly from minute to minute even during clear sky conditions. Here, we may be relying on that noise to distinguish between real data and stale data, and the algorithm could be at a loss because the input GHI data are rounded. If we agree that rounding the data is desireable, and these stale values shouldn't be labeled as such, then tightening the numeric tolerance won't help. The recourse would be to lengthen the default data window (currently 3 points).

2019-06-02 18:33:00+00:00    892
2019-06-02 18:34:00+00:00    893
2019-06-02 18:35:00+00:00    896
2019-06-02 18:36:00+00:00    896
2019-06-02 18:37:00+00:00    896
2019-06-02 18:38:00+00:00    896
2019-06-03 02:35:00+00:00     71
2019-06-03 02:36:00+00:00     71
2019-06-03 02:37:00+00:00     70
2019-06-03 02:38:00+00:00     70
2019-06-03 02:39:00+00:00     70
2019-06-03 02:40:00+00:00     70
2019-06-03 14:03:00+00:00     78
2019-06-03 14:04:00+00:00     79
2019-06-03 14:05:00+00:00     80
2019-06-03 14:06:00+00:00     80
2019-06-03 14:07:00+00:00     80
2019-06-03 14:08:00+00:00     80
2019-06-03 14:09:00+00:00     81
2019-06-03 14:10:00+00:00     81
2019-06-03 14:11:00+00:00     81
2019-06-03 14:12:00+00:00     81
2019-06-03 16:31:00+00:00    315
2019-06-03 16:32:00+00:00    306
2019-06-03 16:33:00+00:00    302
2019-06-03 16:34:00+00:00    302
2019-06-03 16:35:00+00:00    302
2019-06-03 20:32:00+00:00    471
2019-06-03 20:33:00+00:00    475
2019-06-03 20:34:00+00:00    478
2019-06-03 20:35:00+00:00    478
2019-06-03 20:36:00+00:00    478
2019-06-03 20:37:00+00:00    478
2019-06-03 23:48:00+00:00    634
2019-06-03 23:49:00+00:00    633
2019-06-03 23:50:00+00:00    636
2019-06-03 23:51:00+00:00    636
2019-06-03 23:52:00+00:00    636
2019-06-04 16:27:00+00:00    639
2019-06-04 16:28:00+00:00    643
2019-06-04 16:29:00+00:00    645
2019-06-04 16:30:00+00:00    645
2019-06-04 16:31:00+00:00    645
2019-06-04 19:16:00+00:00    982
2019-06-04 19:17:00+00:00    965
2019-06-04 19:18:00+00:00    969
2019-06-04 19:19:00+00:00    969
2019-06-04 19:20:00+00:00    969
2019-06-05 02:54:00+00:00    127
2019-06-05 02:55:00+00:00    111
2019-06-05 02:56:00+00:00     89
2019-06-05 02:57:00+00:00     89
2019-06-05 02:58:00+00:00     89

**Comment by wholmgren** [comment]
The integers come from the data networks, not from our database. If you pull data from the dashboard for a MIDC site you'll see that it has 2 digits past the decimal. Here's a random CRN site with a similar problem for interpolated data but with a different (5 minute) time resolution

https://dashboard.solarforecastarbiter.org/observations/c2fa05fa-7e49-11e9-ad79-0a580a8003e9

<img width="867" alt="Screen Shot 2019-10-28 at 11 02 56 AM" src="https://user-images.githubusercontent.com/4383303/67704534-871e2b00-f972-11e9-9ef2-93301c16ebe2.png">

**Comment by wholmgren** [comment]
I'm confused. I just downloaded the following csv for the MIDC site at UA and it has data after the decimal

```
# observation_id: 9f657636-7e49-11e9-b77f-0a580a8003e9
# metadata: https://api.solarforecastarbiter.org/observations/9f657636-7e49-11e9-b77f-0a580a8003e9/metadata
timestamp,value,quality_flag
20191027T00:00:00+0000,95.9361,514
20191027T00:01:00+0000,92.5305,514
20191027T00:02:00+0000,89.205,514
20191027T00:03:00+0000,85.7881,514
20191027T00:04:00+0000,82.5313,514
20191027T00:05:00+0000,79.3887,514
20191027T00:06:00+0000,76.2459,514
20191027T00:07:00+0000,73.0174,514
20191027T00:08:00+0000,69.8175,514
20191027T00:09:00+0000,66.6975,514
20191027T00:10:00+0000,63.5712,514
...
```

**Comment by cwhanse** [comment]
> I'm confused. I just downloaded the following csv for the MIDC site at UA and it has data after the decimal

So it does. I misread your earlier note and expected to see fractional data at the Monahans site, where I only get round numbers for GHI. Same (only round numbers) for GHI from the Seattle UW WA site. If the data are rounded, that's happening at the source then?

**Comment by wholmgren** [comment]
Integers in the data loggers maybe? At the risk of getting into a difficult discussion about uncertainty, isn't the rounding vs truncation issue well within the uncertainty of even the best and best maintained instruments?

**Comment by cwhanse** [comment]
> Integers in the data loggers maybe? At the risk of getting into a difficult discussion about uncertainty, isn't the rounding vs truncation issue well within the uncertainty of even the best and best maintained instruments?

Could be; I'm not questioning the data's validity. The issue here with stale/interpolated data detection is that the algorithm assumes precision that's been removed by rounding. The algorithm finds linear features where three successive values are nearly the same (stale) or if two successive differences are nearly equal (interpolation). Data that are rounded to integers more easily satisfy these criteria.

**Comment by wholmgren** [comment]
These functions already accept a `window` kwarg, so perhaps we should call them with longer windows for subhourly data. Several functions in `validation.tasks` call these functions a few times, so I guess we'd want to define something like `validation.validator.stale_interpolated_window(interval_length)` or `validation.validator.stale_window(interval_length)` and `validation.validator.interpolated_window(interval_length)`

**Comment by wholmgren** [comment]
@cwhanse can you propose some recommendations for how to set the window length (perhaps as a function of interval_length) to avoid spurious detection of stale and interpolated values? There are currently too many false positives to expose these flags in the report.

**Comment by cwhanse** [comment]
I need to get back to my office and pick up where I was, when we were diagnosing this problem.

**Comment by cwhanse** [comment]
@wholmgren I've got some ideas to tame the false positives for GHI.  Most of the false positive results from `detect_stale_values` and `detect_interpolation` are from `detect_interpolation`.  Stale positives are a subset of the interpolation positives, since stale detects flat segments and interpolation detects any linear segments.

I'd suggest two things:

1. Exclude nighttime from being labeled as stale or interpolated. I wouldn't change the input to the `detect_` functions, I'd AND the result somewhere else with the day/night flag. I don't follow the task code enough to do a PR, but it seems like it would involve adding (or using the output of) ` check_irradiance_day_night` in `validate_daily_ghi`

2. Default the `window` parameter to 6. I did some testing with two months of data from Monohans (5min), UWashington (1min) and the MIDC UArizona GHI data.  Defaulting to 6 reduces the false positive rate (for daylit times) to:

| Site              | window = 3  |  window = 6  |
| --- | --- | --- |
| Monahans | 10.5% | 0.32% |
| UWashington | 18.6% | 2.36% |
| UArizona | 0.16% | 0.0% |

The reason that the UArizona site has a much lower false positive rate is that the data carry precision below 1 W/m2 (could be argued that the precision is false, but that's not the point here). The Monohans and UWashington data have a resolution of 1 W/m2, which means that its more likely that the difference between successive values is equal when irradiance is not changing much.  The chance of false positive increases as data frequency decreases.

Interestingly, the UWashington data looks like it _has_ a few interpolated periods, for example:

timestamp	value	stale	interp
2020-05-18 12:51:00+00:00	16.0	False	False
2020-05-18 12:52:00+00:00	17.0	False	False
2020-05-18 12:53:00+00:00	18.0	False	True
2020-05-18 12:54:00+00:00	19.0	False	True
2020-05-18 12:55:00+00:00	20.0	False	True
2020-05-18 12:56:00+00:00	21.0	False	True
2020-05-18 12:57:00+00:00	22.0	False	True
2020-05-18 12:58:00+00:00	23.0	False	True
2020-05-18 12:59:00+00:00	24.0	False	True
2020-05-18 13:00:00+00:00	25.0	False	True
2020-05-18 13:01:00+00:00	26.0	False	True
2020-05-18 13:02:00+00:00	27.0	False	True
2020-05-18 13:03:00+00:00	29.0	False	False
2020-05-18 13:04:00+00:00	30.0	False	False
2020-05-18 13:05:00+00:00	31.0	False	False
2020-05-18 13:06:00+00:00	33.0	False	False

**Comment by wholmgren** [comment]
Thanks @cwhanse that seems like a reasonable change. Do you have any tests or a sense of how this will effect tests for data with longer intervals? My understanding is that this will make it more likely that we miss some stale or interpolated values, but that's probably an ok tradeoff. Alternatively we can add some logic for setting the window size based on interval length, as discussed previously.

**Comment by cwhanse** [comment]
> Thanks @cwhanse that seems like a reasonable change. Do you have any tests or a sense of how this will effect tests for data with longer intervals? 

I could repeat the statistics for longer times, if that's of interest. I don't have a data set handy that has known stale/interpolation issues, which would be a better test case.

> My understanding is that this will make it more likely that we miss some stale or interpolated values,

Yes.

>  but that's probably an ok tradeoff.

I agree.

> Alternatively we can add some logic for setting the window size based on interval length, as discussed previously.

I agree with this as well. We could consider adding a detector for lower precision data and take that into account when setting the window length.

**Comment by wholmgren** [comment]
It feels a little arbitrary, but how about window = 6 for subhourly data and window = 3 for hourly or longer?

The precision idea sounds useful but I'd rather let pvanalytics take the lead on that.

**Comment by cwhanse** [comment]
> It feels a little arbitrary, but how about window = 6 for subhourly data and window = 3 for hourly or longer?

OK with me.

**Comment by wholmgren** [comment]
@alorenzo175 I'm assuming you're still in favor of a derived flag (discussed above https://github.com/SolarArbiter/solarforecastarbiter-core/issues/124#issuecomment-499657746). So I'm wondering how to proceed. A PR to adjust the window length is straightforward, but the derived flag seems like a challenge to fit into the bitmask model. 2 PRs? Ultimately I think the dashboard should only present "DAYTIME STALE VALUES" and "DAYTIME INTERPOLATED VALUES" or similar.

**Comment by alorenzo175** [comment]
Yes, I'm still in favor of a derived flag. Any code that interacts with the flags should (double check to be sure) be going through ``validation.quality_mapping.convert_mask_into_dataframe`` first, so that's where the derived flag columns should be added. Up to you on 1 or 2 PRs
```

**Comment by wholmgren** [comment]
Documenting an example as of beta6:

https://dashboard.solarforecastarbiter.org/observations/9655385a-7e49-11e9-9080-0a580a8003e9?start=2020-05-30T02%3A00Z&end=2020-06-01T02%3A00Z

<img width="801" alt="Screen Shot 2020-06-02 at 3 23 31 PM" src="https://user-images.githubusercontent.com/4383303/83575745-141afb00-a4e5-11ea-85da-26ce306d45c7.png">
