### ISSUE TITLE
report signature

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#157]
Reports should include a signature that can be used to check authenticity.

**Comment by alorenzo175** [comment]
Will used GPG to make a detached signature, and also provide a SHA 256 checksum. This will only be relevant for file downloads, and we first need to make sure html/pdf generation is reproducible. Right now, adding the timeseries and scatter plots later results in a document with different fields each time it is produced resulting in a checksum that changes each time the same report is generated. We could not include those graphs in downloads, or store static images in the template that is saved to the database and just keep those in the downloads.

**Comment by wholmgren** [comment]
I'm guessing this will also be sensitive to report/template versions. I think the goal is to ensure that the metrics and input data are the same, not that the display is the same. I guess we could have two signatures if we needed to.

**Comment by alorenzo175** [comment]
My idea of "report signature" was to ensure that someone who was given or downloaded a report could verify that we generated the report and that it wasn't tampered with. Since we will generate a download on the fly from the raw report stored in SQL, we also need to dynamically generate the GPG signature and checksums *of the generated report*.

I think what your referring to might be better described as verifying the forecast/obs values used to generate the metrics is the same now as when those metrics where generated. To accomplish that, we should store a checksum of the data when the raw report is created, and then check that against a checksum of the data displayed in the timeseries/scatter plots (or in downloads of that data).

**Comment by wholmgren** [comment]
makes sense
