### ISSUE TITLE
report downloads

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#158]
Reports should be downloadable in html and pdf formats. Perhaps two issues.

**Comment by alorenzo175** [comment]
HTML is not so problematic; we just need a standalone template to inject the body into. PDF also isn't so bad; [weasyprint](weasyprint.org) looks like a good option and is supported by pandoc. If we are only going to support HTML and PDF, it may make the most sense to just make the standard report in HTML (instead of pandoc markdown) and use weasyprint directly to make the PDF.

**Comment by wholmgren** [comment]
I still think it would be really cool to support notebooks, so all other things being  I’d rather not give up that option. But if it’s worth dropping markdown to do that then ok.

**Comment by alorenzo175** [comment]
The easiest way to support HTML, PDF, and notebooks might be to start with a notebook. Then, use nbconver to convert to HTML and PDF (using a nbconvert.preprocess to automatically convert Bokeh plots to SVG) like these examples

[quickstart.zip](https://github.com/SolarArbiter/solarforecastarbiter-core/files/3935470/quickstart.zip)

**Comment by alorenzo175** [comment]
We decided on separate templates for HTML and PDF. HTML downloads are currently implemented in the dashboard.
