### ISSUE TITLE
Brier Score: implementation details

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#233]
Related to #115 and discussion during the team call 10/24:

The Brier Score (BS) is usually defined in terms of a single event (e.g. probability of rain/no rain), but can be generalized to be calculated for a (finite) set of events. Given that the metrics module is meant to support evaluating forecasts for both single events (e.g. probability of power < 10 MW at time t) and potentially multiple events (e.g. probability of power < 10 MW at time t, < 20 MW at time t, etc.), there are a few open questions in terms to implementation:

1. Should the Brier Score be implemented only for single events, with Solar Arbiter returning one Brier Score per event in the case where the evaluated forecast covers `N` probability bins (i.e. `N` probability bins in the forecast, then return `N` Brier Scores)? Or should we use the multi-category/generalized definition of Brier Score (i.e. `N` probability bins in the forecast, then return a single Brier Score)?
2. Does the Brier Score need to be computed in terms of a PDF (e.g. forecasts of probability of 0 MW < x <= 10 MW, 10 MW < x <= 20 MW, etc.), rather than a CDF? If not, does the Brier Score from a CDF have any differences in interpretation, assumptions, etc. from Brier Score from a PDF?

There are related questions to the above (e.g. interpolation), but the above cover the main points.

**Comment by dplarson** [comment]
Based on today's discussion, tagging @cwhanse and @MrWindAndSolar but others are welcome to chime in.

**Comment by dplarson** [comment]
For reference, my reading of the literature on Brier Score is that:
1. we should use the multi-category definition of Brier Score
2. the Brier Score should only be computed from a (discrete) PDF representing mutually-exclusive (and finite) events (e.g. 0 < x <= 10, 10 < x <= 20, etc.) and the metrics module should convert the input CDF forecasts to PDF forecasts

**Comment by wholmgren** [comment]
My reading may not be as extensive as yours, but I am coming to the opposite conclusion. I've not seen the multi-category Brier score frequently used in the atmospheric sciences or solar forecasting literature, whereas the binary Brier score is frequently used. Wilks "Statistical Methods in the Atmospheric Sciences" states "The Brier Score as expressed in Equation 8.36 [the binary score] is nearly universally used, but it differs from the score as originally introduced by Brier..." Seems that avoiding the multi-category Brier score will also save us implementation headache.

**Comment by wholmgren** [comment]
A little more distracted reading later, and I am -1 on supporting a multi-category Brier score because it does not account for magnitude of error. Is there a use case that requires this property? I don't think so. Our "evaluate an event forecast" use case was meant to describe binary events, and otherwise we're always talking about evaluations that benefit from magnitude penalties.

**Comment by dplarson** [comment]
I see your point and while I think the multi-category Brier score better matches how probabilistic solar forecasts are likely to be generated/evaluated, I am not against implementing the binary-event Brier score for now and then re-visiting this topic if stakeholders raise an issue.

If others agree, then the end result is that the metrics module would return (to the report) a Brier score per event (e.g. one Brier score for x < 10 MW, one Brier score for x < 20 MW, etc.).

**Comment by wholmgren** [comment]
> I think the multi-category Brier score better matches how probabilistic solar forecasts are likely to be generated/evaluated

When would you want to evaluate a solar forecast using the multi-category Brier score instead of CRPS? Reducing the parameter space over which users can evaluate forecasts makes things easier for users and for us, so I'd rather not support it unless there is a reason. Sorry, I'm not trying to win a debate, only trying to understand if I'm missing something.

> If others agree, then the end result is that the metrics module would return (to the report) a Brier score per event (e.g. one Brier score for x < 10 MW, one Brier score for x < 20 MW, etc.).

That works for me. Another option is the Brier score metric should only accept a time series of single event forecasts (so a 1D array/Series rather than a 2D array/DataFrame).

**Comment by cwhanse** [comment]
I don't see this as a choice between the "event" Brier score or the "multi-category" score.  The two cases are distinguished by the number of outcomes in the probability forecast at a point in time, not by the formula for the score.  In Wilks, the Brier score is Brier's original formula restricted to a binary probability space. Brier's original score is presented as the Ranked Probability Score (Eq. 8.50b) which appears to be the discrete version of the CRPS (Eq. 8.54a).

One challenge will be applying any of these scores to quantile-indexed forecasts (forecast value is a quantile of power, with fixed quantiles over time) because the power levels will change throughout the day. As formulated, these scores apply to probability events, not to quantile levels, so it is not clear to me how they are used for quantile-indexed forecasts.

**Comment by wholmgren** [comment]
> Brier's original score is presented as the Ranked Probability Score (Eq. 8.50b)

Here's my understanding... RPS reduces to the binary Brier score, but it is not the same as the original multi-category Brier score. RPS evaluates the cumulative probabilities, whereas the original multi-category Brier score evaluates the discrete probabilities. Consider an observation and two forecasts for three categories:

```
obs = (0, 0, 1)
fx1 = (0.2, 0.5, 0.3)
fx2 = (0.5, 0.2, 0.3)

Brier = sum( (f_i - o_i)^2 )
Brier fx1 = .2^2 + .5^2 + .7^2
Brier fx2 = .5^2 + .2^2 + .7^2

RPS = sum( (F_i - O_i)^2 )
RPS fx1 = 0.2^2 + 0.7^2 + 0^2
RPS fx2 = 0.5^2 + 0.7^2 + 0^2
```

The multi-category Brier score is the same for these two forecasts, but the RPS is not.

In my opinion, Wilks confuses the situation by stating that "The ranked probability score is essentially an extension of the Brier score (Equation 8.36) to the many-event situation." 

> One challenge will be applying any of these scores to quantile-indexed forecasts (forecast value is a quantile of power, with fixed quantiles over time) because the power levels will change throughout the day. As formulated, these scores apply to probability events, not to quantile levels, so it is not clear to me how they are used for quantile-indexed forecasts.

Well, we have ordered pairs on a CDF at each time, so in principle we have the information we need. For implementation, maybe we will need to manually loop over the time index. However, I don't know if that's actually a valid use of these metrics (which may have been your point).

**Comment by dplarson** [comment]
In response to your earlier comment @wholmgren:

> When would you want to evaluate a solar forecast using the multi-category Brier score instead of CRPS? Reducing the parameter space over which users can evaluate forecasts makes things easier for users and for us, so I'd rather not support it unless there is a reason. Sorry, I'm not trying to win a debate, only trying to understand if I'm missing something.

I wholeheartedly appreciate this discussion and you explaining your points. And I agree that having CRPS circumvents the need for a multi-category Brier score.

Also, to clarify: my overarching viewpoint is that it's more "natural" to want to evaluate how a probabilistic forecast's distribution matches observations (e.g. CRPS). But at the same time, I do see value in metrics that just evaluate a forecast that is a value + probability pair (e.g. binary-event Brier score) since that also matches a potential use case. So basically, I see no problem as long as there are metrics for both scenarios.
