### ISSUE TITLE
fix determistic.pearson_correlation_coeff

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#277]
`and`/`or` and `nan` issues as discussed here https://github.com/SolarArbiter/solarforecastarbiter-core/pull/224#discussion_r352910495

**Comment by dplarson** [comment]
For the `len(obs) != len(fx)` and `len(obs) < 2` issues, we could just add a try-except statement to catch the `ValueError` raised by `scipy.stats.pearsonr()`:

```python
try:
    r, _ = sp.stats.pearsonr(obs, fx)
except ValueError as e:
    raise e
    # alternatively: return `r = np.nan` (i.e. catch, but don't raise the error)
return r
```

In the case where `obs` or `fx` contains `nan` values, this try-catch setup seems to result in `nan` as the output (i.e. no `ValueError` is raised).

So should we a) use the `ValueError` from `scipy.stats.pearsonr()` or b) add the checks to `determistic.pearson_correlation_coeff()`?

**Comment by alorenzo175** [comment]
I think catching the ValueError and returning nan is most consistent, e.g. mae will also return nan if any nan values exist in obs or fx since it's using ``np.mean``

**Comment by wholmgren** [comment]
> e.g. mae will also return nan if any nan values exist in obs or fx since it's using np.mean

is that the behavior we want? Do we need to replace all instances of `np.mean` with `np.nanmean`?

**Comment by wholmgren** [comment]
same concern about `np.sum`, `ndarray.min`, `ndarray.max`

**Comment by dplarson** [comment]
While the `len(obs) != len(fx)` and `len(obs) < 2` issues should definitely be addressed, I'm wondering if we should stick with assuming that NaN values should already have been removed from `obs` and `fx` prior to being passed to the metric functions. Thoughts?

Note: This has been my assumption while writing the metric functions, hence the use of `np.mean()` instead of `np.nanmean()` and lack of checks for NaN values. But I'm not against having more robust checks in the metric functions.

**Comment by wholmgren** [comment]
I’m ok with keeping the basic metrics functions sensitive to nans. Let’s get the calling modules in shape to handle them. And we should add tests for nan behavior.
