### ISSUE TITLE
Explicitly handle NaN data in metrics

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-core#285]
The current implementation of the metrics subpackage assumes that the inputs have already been pre-processed to remove NaN values. But we don't yet have code in place to handle the pre-processing.

At minimum, we need to explicitly deal with the NaN values, but we should also confirm that the metrics subpackage properly handles flagged data from the validation subpackage.

**Comment by wholmgren** [comment]
We might want to make a series of smaller issues, though I'm not yet sure how to break them up.

Maybe step one is that is that we drop all missing data from both forecasts and observations and we report that we've done so in the data validation section of the report. 

Steps two through N could be handling validation results (creating nans or 0s as appropriate), reporting validation results (currently just static dummy data in the report), and eventually exposing a few options to users.

The plotting module has some quality flag wrangling code that might worth copying or refactoring for metrics:

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/solarforecastarbiter/plotting/timeseries.py#L312-L318

**Comment by awig** [comment]
@dplarson @wholmgren 
The assumption I've been making is that the validation is done and the `quality_flags` that are given are included for an `Observation` than the `report.main.validate_resample_align` handles them as specified (right now this is only using the exclude function). Since this only applies to observations and I would assume the validation would capture any nans in the observation. Is this a safe assumption stil or do we have to have an extra step in metrics as this issue suggests?  Is this also needed for `Forecast` data? However, before we had discussed that we do not want to change the forecasts at all, but I see how practically this cannot be done for nans.

**Comment by wholmgren** [comment]
Thanks @awig. I had forgotten about some of that. 

We do not store missing data in the database, so we cannot store a `MISSING` flag for any missing points. So the plotting code linked to above derives the flag.

If I understand correctly, the `reports.main.validate_resample_align` function takes data that does not contain missing data, calls `preprocessing.apply_validation` on that data, and then may create missing data by calling `preprocessing.resample_and_align`.

**Comment by wholmgren** [comment]
>Is this also needed for Forecast data? However, before we had discussed that we do not want to change the forecasts at all, but I see how practically this cannot be done for nans.

Yes. We don't want to modify forecasts or apply any data validation, but missing forecasts are a special case. If we're just excluding observations where forecasts are missing (reasonable for research purposes) then that's not modifying the forecast. But in a trial situation we'll need to have a penalty for a missing forecast, and that will require modifying the time series at some point in the metrics code.

**Comment by alorenzo175** [comment]
> We do not store missing data in the database, so we cannot store a MISSING flag for any missing points.

Not entirely true (I'm pretty sure) since you can upload ``nan``. It's still true that the MISSING flag is derived and not stored though.

**Comment by alorenzo175** [comment]
> Maybe step one is that is that we drop all missing data from both forecasts and observations and we report that we've done so in the data validation section of the report. We don't (yet) need to state how many we dropped or if they were dropped before or after resampling.

Steps two through N could be handling validation results (creating nans or 0s as appropriate), reporting validation results (currently just static dummy data in the report), and eventually exposing a few options to users.

I agree that we can start by dropping nans from both fx/obs when there is a nan in either, and then move on to exposing options to e.g. drop missing observations but set missing forecasts to zero

**Comment by awig** [comment]
To clear things up I have a question and sorry for asking them here instead of just referencing https://solarforecastarbiter.org/usecases/

* When the data is stored and subsequently queried from the database, absolutely no modifications are made to the data (whether forecast or observation) but the quality checks (validation) are applied to observations?

> If I understand correctly, the reports.main.validate_resample_align function takes data that does not contain missing data, 

Just to be sure, "missing data" you are referring to is no nan values or no gaps in the data for the given interval?

> calls preprocessing.apply_validation on that data, and then may create missing data by calling preprocessing.resample_and_align.

I had forgotten, sorry about that I think we discussed this at some point a ways back.  I agree with the methods described earlier, but we should also consider how the preprocessing of the observations is taken into account with the quality flags. I would foresee the user potentially getting confused if we provide multiple options to handle the data at multiple stages.

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/76cabc77cb574ac22548cb1aef9ed1aeaf969c5e/solarforecastarbiter/metrics/preprocessing.py#L86 
```python

    # Resample observation
    closed = datamodel.CLOSED_MAPPING[fx.interval_label]
    obs_resampled = data[obs].resample(fx.interval_length,
                                       label=closed,
                                       closed=closed).mean()

    # Align (forecast is unchanged)
    # Remove non-corresponding observations and
    # fill missing observations with NaN
    fx_aligned, obs_aligned = data[fx].align(obs_resampled, 'left')
```

**Comment by wholmgren** [comment]
> When the data is stored and subsequently queried from the database, absolutely no modifications are made to the data (whether forecast or observation) but the quality checks (validation) are applied to observations?

Correct

> Just to be sure, "missing data" you are referring to is no nan values or no gaps in the data for the given interval?

I was thinking that `validate_resample_align` takes data that does not contain nan values because the API never returns nans because the database never stores nans. But @alorenzo175 pointed out (or is pretty sure) that the database does store nans when data is uploaded with formats as described [here](https://solarforecastarbiter.org/2019/03/26/Data-Exchange-Revisions.html#missing-irregular-and-regular-data). @alorenzo175 can you confirm before we make a decision on how to tackle things? I thought the API might drop the timestamps with missing data before inserting into the database.

In any case, I know that interval length is enforced in each upload, but two uploads that are not contiguous will result in missing data only at the resample step (after validation). For example the following series would result from a user uploading 1 hour data at 00, failing to upload data at 01, and then uploading data gain at 02:

```
In [143]: s = pd.Series([0, 2], pd.DatetimeIndex(['20190101 0000', '20190101 0200']))

In [144]: s
Out[144]:
2019-01-01 00:00:00    0
2019-01-01 02:00:00    2
dtype: int64

In [145]: s.resample('1h').mean()
Out[145]:
2019-01-01 00:00:00    0.0
2019-01-01 01:00:00    NaN
2019-01-01 02:00:00    2.0
Freq: H, dtype: float64
```

The nan at 01 causes a problem for the metrics functions.

> I would foresee the user potentially getting confused if we provide multiple options to handle the data at multiple stages.

I agree, but I don't know if we can avoid handling validation at multiple stages. We don't have to expose everything to the user, though.

Additional processing is needed during resampling to handle situations in which higher frequency data with gaps is used to calculate lower frequency data. For example, consider the following 15 minute data:

```
In [126]: pnts = int(60/15*3)

In [135]: s = pd.Series(list(range(pnts)), pd.date_range('20190101', freq='15min', periods=pnts))

In [136]: s.iloc[5] = np.nan

In [137]: s.iloc[-3:] = np.nan

In [138]: sfunky = pd.concat([s.iloc[[0, 3]], s.iloc[4:]])

In [139]: sfunky
Out[139]:
2019-01-01 00:00:00    0.0
2019-01-01 00:45:00    3.0
2019-01-01 01:00:00    4.0
2019-01-01 01:15:00    NaN
2019-01-01 01:30:00    6.0
2019-01-01 01:45:00    7.0
2019-01-01 02:00:00    8.0
2019-01-01 02:15:00    NaN
2019-01-01 02:30:00    NaN
2019-01-01 02:45:00    NaN
dtype: float64
```

How do you calculate hourly data from that? We currently do this:

```
In [140]: sfunky.resample('1h').mean()
Out[140]:
2019-01-01 00:00:00    1.500000
2019-01-01 01:00:00    5.666667
2019-01-01 02:00:00    8.000000
Freq: H, dtype: float64
```

maybe we need options like this:

```
In [141]: sresampled = sfunky.resample('1h').agg(['mean', 'count'])

In [142]: sresampled['mean'].where(sresampled['count'] > 2)
Out[142]:
2019-01-01 00:00:00         NaN
2019-01-01 01:00:00    5.666667
2019-01-01 02:00:00         NaN
Freq: H, Name: mean, dtype: float64
```

and we need to report out why the resampled data is missing. This came up in the September call.

**Comment by alorenzo175** [comment]
> @alorenzo175 can you confirm before we make a decision on how to tackle things? I thought the API might drop the timestamps with missing data before inserting into the database.

I can confirm that one can definitely upload NaNs and they are stored in the database. We did this to be able to enforce uploading forecast timeseries that conform to interval length etc.

**Comment by dplarson** [comment]
Based on the above discussion, it seems we need code that does the following:
1. a (more) robust resampling of observations (e.g. if resampling to 1-hour, set as that 1-hour as NaN if less than 50% of observations within that 1-hour are non-NaN values), with some level of user input
2. dropping any time indices where observations or forecasts have NaN

Item 2 is more clear-cut, whereas item 1 would likely have a few different cases.
