### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by cwhanse** [SolarArbiter/solarforecastarbiter-core#30]
Exceptions raised in e.g. Validator are not passed up to be exposed to a framework user.  One idea is to have functions to return Exceptions to the API so that they can be reported.

**Comment by wholmgren** [comment]
Do you have a particular situation in mind? In general I think the core code should handle validation exceptions and set the appropriate quality flags in the database rather than exceptions going up to the user. Certainly misformatted data (e.g. bad timestamps) will be immediately reported to the user at upload time.

**Comment by cwhanse** [comment]
I don't have an example, just a thought that we may run into a situation where resolving an error may require a message back to the user.

**Comment by cwhanse** [comment]
Closing this general issue, we can discuss messaging when a specific example comes up.
