### ISSUE TITLE
no reference forecasts for RTC site since Feb

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#383]
https://dashboard.solarforecastarbiter.org/forecasts/single/a813c4b4-99fc-11e9-8cfc-0a580a8200c9

![bokeh_plot(54)](https://user-images.githubusercontent.com/4383303/78396235-d876ba00-75a3-11ea-958c-3525595485ea.png)

not sure how widespread this is at the moment.

**Comment by alorenzo175** [comment]
Seems like the issue is that the API actually gets overloaded when trying to post forecasts and the job is terminated because a POST fails. A few things we should do to avoid this:

1. Make sure these errors are reported in sentry so we actually know something is wrong 
2. Handle retries in posting values in the core api module
3. Add checks (maybe using /latest) to ensure forecasts are being updated

**Comment by alorenzo175** [comment]
Ah, I actually think the problem is that the timeout is unset for the reference nwp, defaulting to 1 minute so sometimes the job scheduler kills the job before it produces all the reference forecasts. 

Checks should still be implemented, but it looks like retries are handled and sentry errors for other jobs are logged properly.

**Comment by alorenzo175** [comment]
SolarArbiter/solarforecastarbiter-api#231 with an adjustment to the worker timeout solves this
