### ISSUE TITLE
Fix report data validation table for new QualityFlagFilter fields

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#589]
and the paragraph of text after it

![image](https://user-images.githubusercontent.com/4625457/96056592-de473500-0e3b-11eb-805f-b0ff99b3474c.png)

**Comment by wholmgren** [comment]
Hmm this is not trivial. Here's a more complicated filter spec and the formatted report output:

```
        "filters": [
            {
                "quality_flags": [
                    "USER FLAGGED"
                ],
                "discard_before_resample": true,
                "resample_threshold_percentage": 10.0
            },
            {
                "quality_flags": [
                    "LIMITS EXCEEDED"
                ],
                "discard_before_resample": true,
                "resample_threshold_percentage": 10.0
            },
            {
                "quality_flags": [
                    "NIGHTTIME"
                ],
                "discard_before_resample": false,
                "resample_threshold_percentage": 10.0
            },
            {
                "quality_flags": [
                    "NIGHTTIME",
                    "CLEARSKY"
                ],
                "discard_before_resample": false,
                "resample_threshold_percentage": 20.0
            }
        ],
```

<img width="1135" alt="Screen Shot 2020-10-15 at 7 55 50 PM" src="https://user-images.githubusercontent.com/4383303/96207613-76b6e580-0f20-11eb-8c2c-cad4392ad78e.png">

In `preprocessing.py`, the `counts` dict for one pair is:

```
{'LIMITS EXCEEDED': 0, 'USER FLAGGED': 0, 'ISNAN': 0, 'DISCARD BEFORE RESAMPLE: USER FLAGGED OR ISNAN': 0, 'DISCARD BEFORE RESAMPLE: LIMITS EXCEEDED OR ISNAN': 0, 'NIGHTTIME OR ISNAN': 60, 'NIGHTTIME OR CLEARSKY OR ISNAN': 85}
```

We get multiple tables because `body.html` iterates over `report.report_parameters.filters`. But most of the values are not printed in the html tables because the dict keys don't match the original quality filter flag names in `macros.validation_table`. 

One approach is to make a simple table of the quality filter metadata, then make a simple table of the counts dict. This seems straightforward.

Another approach would be to keep an association between specific filters and the results. Might need to add a lot more metadata to `datamodel.ValidationResult` and create those within the `filter_resample` functions. This would let us avoid the hack of prepending 'DISCARD BEFORE RESAMPLE' to some of the keys.

Yet another approach might be separate tables for discard before resampling and discard after resampling. Perhaps two different counts dicts could solve this without too much effort. Or could add True/False to keys or values, but if you're doing this then you probably just want a better datamodel object. 

I also overlooked a note I made on the `PreprocessingResult` calculation, so a bad number shows up in the Data Resampling and Alignment table:

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/99c3456d32ae1e25935ab1129f1a9d919ad4fc5c/solarforecastarbiter/metrics/preprocessing.py#L741-L748
