### ISSUE TITLE
reports for deterministic fx show event summary statistics table

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#694]
[for example](https://dashboard.solarforecastarbiter.org/reports/bedd4742-ad24-11eb-947e-0a580a8002ec#summarystats)

<img width="854" alt="Screen Shot 2021-07-23 at 9 42 32 AM" src="https://user-images.githubusercontent.com/4383303/126814422-15d3e000-1348-4e39-91d6-9c8f85d9e15b.png">

**Comment by lboeman** [comment]
Added a comment in the problematic code that references this issue and will try to summarize the cause here.
The issue here was not detectable when using the core cli to generate reports. The core library's helper functions take the API Response's object_pairs that look something like this:
```
"object_pairs": [
{
"aggregate": "0f59de55-2f0e-436a-8ea9-fb197b396fd3",
"cost": null,
"forecast": "c1058bd0-c3da-4141-92c6-496be27f264d",
"forecast_type": "forecast",
"observation": "5bf24aaf-36fe-45d8-956d-da6551803aa4",
"reference_forecast": null,
"uncertainty": null
}
],
```
And fill in forecast/observation/aggregate with the appropriate datamodel objects using the helper here: https://github.com/SolarArbiter/solarforecastarbiter-core/blob/fa8fb9961e8135c52395dd138061aaedf6915e76/solarforecastarbiter/io/api.py#L1063

Since the `raw_report` field of a completed report object already includes this metadata in the `Report.raw_report.processed_forecasts_observations[<index>].forecast/observation.original`, the dashboard avoids loading this a second time by setting `Report.report_parameters.object_pairs` to an empty list before instantiating a Report object for use with the `solarforecastarbiter.reports.template.py` functions.

The code as written functioned in core with the aid of the above mentioned helper, but when passed an empty list the `all(x.forecast is datamodel.EventForecast for x in report_parameters.object_pairs)` test always returned true. The fix implemented is to use the original forecast from the processed pairs, since they should always exist for a completed report that is being rendered.
