### ISSUE TITLE
processed forecast observations csv does not account for different time indices

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-core#707]
From a reference data report:

```
,University of<br>Arizona OASIS ghi<br>60m ending,University of<br>Arizona OASIS ghi<br>60m beginning,University of<br>Arizona OASIS ghi<br>15m beginning,University of<br>Arizona OASIS ghi 5m<br>beginning,University of Arizona OASIS Day Ahead GFS ghi,University of Arizona OASIS Current Day NAM ghi,University of Arizona OASIS Intraday HRRR ghi,University of Arizona OASIS Intraday RAP ghi,University of Arizona OASIS Hour Ahead Persistence ghi,University of Arizona OASIS Fifteen-minute Ahead Persistence ghi,University of Arizona OASIS Five-minute Ahead Persistence ghi,University of Arizona OASIS Day Ahead Persistence ghi
2020-12-31T17:00:00-07:00,23.8143,23.8143,23.8143,23.8143,42.3903,41.6174,118.333,41.6174,2.48807,7.29392,47.1064,131.407
2020-12-31T18:00:00-07:00,nan,nan,nan,17.8177,nan,nan,nan,nan,nan,nan,21.1479,nan
2020-12-31T19:00:00-07:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
2020-12-31T20:00:00-07:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
```

There are both hourly and subhourly forecasts in this file but we only see hourly timestamps.

**Comment by lboeman** [comment]
The issue here is caused by building a CSV from the data stored in the report for plotly to use. The timeseries plot has separate javascript arrays for values and time indices, and attempts to zip them together to create these files. As seen in #713, if one pair does not include data to start, it gets it completely wrong. 

This should probably be separated into separate CSVs for each forecast/observation pair, or possibly per unique interval_length. Without separating into pairs/by interval lengths, we'd be forced to fill with NaN for longer interval lengths, which misrepresents the data.
