### ISSUE TITLE
for apisession.get_*_values add option to account for interval_label

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-core#80]
Currently, start and end describe the range of timestamps expected in the return value of the methods. If interval_label of the model is accounted for, start and end can instead describe the time range that the forecast/observation are valid over. For example, if a forecast has ``interval_label = beginning`` and ``interval_length = 1hr``, a request from ``2019-05-01T1200Z``to ``2019-05-01T1400Z`` will return a timeseries with time labels ``2019-05-01T1200Z`` and ``2019-05-01T1300Z`` since these values represent the entire following hour.

Both conventions can be useful. For example, when plotting something over a plot range, specifying the range in terms of the expected output can be useful. When requesting data to compare forecasts and observations, specifying the range in the second way returns values that only use/contain information from the range.

**Comment by wholmgren** [comment]
Nice summary

**Comment by wholmgren** [comment]
The functions in `reference_forecasts.persistence` assume that data returned by the API accounts for interval label. As a result, the `reference_forecasts.main.run_persistence` wrapper of these functions produces slightly incorrect forecasts or fails due to the length of forecast being 1 element longer than the index.
